In [ ]:
import numpy as np
A = np.array([
    [2, 3],
    [4, 5]
])

B = np.array([
    [1, 2],
    [3, 4]
])

In [ ]:
# addition, multiplication and division
print ("Addition" , A + B)
print ("Multiplication", A * B)
print ("Division", A / B)
print ("Scalar Multiplication", 2 * B)
print ("Scalar Division",  B / 2)


Addition [[3 5]
 [7 9]]
Multiplication [[ 2  6]
 [12 20]]
Division [[2.         1.5       ]
 [1.33333333 1.25      ]]
Scalar Multiplication [[2 4]
 [6 8]]
Scalar Division [[0.5 1. ]
 [1.5 2. ]]


In [ ]:
print(np.dot(A , B)) # return a scalar  (3 * 1) + (4 * 2)

[[11 16]
 [19 28]]


In [ ]:
print(np.linalg.norm(A)) # return a scalar root(3 ^ 2 * 4 ^ 2)

7.3484692283495345


In [ ]:
print("Element wise multiplication\n", A * B) # Element wise multiplication
print("rows × columns\n", A @ B) # rows x column
print(A.shape)

Element wise multiplication
 [[ 2  6]
 [12 20]]
rows × columns
 [[11 16]
 [19 28]]
(2, 2)


In [ ]:
# vector and numpy array -> vector (we will have [age, salary] @ Weights W = [[]]).
# Weights : How much should each feature contribute to the prediction? from training ML model generates weights
# shape -> (2 x 3)(3 x 1)=(2 x 1)
#Weight influece the feature

x = np.array([10, 20])
print(x @ A)

[100 130]


In [ ]:
# bias uplift the o/p
# y = W + b
b = np.array([5,10])
print("O/P with bias : " , (x @ A) + b)

O/P with bias :  [105 140]
